---
provider: aws
# Your AWS Account ID
aws_account_id: 691697225003

# Prefix to be added to created resources
prefix: korbit

# AWS S3 bucket region where Terraform will store state
tf_state_bucket_region: us-east-1

# Github username or organization, this can be used by Flux2 to auto configure
# Github bootstrap
github_owner: soyip
